" Use the Solarized Dark theme
set background=dark
colorscheme seoul256
" Use 14pt Monaco
set guifont=Monaco:h12
" Don’t blink cursor in normal mode
set guicursor=n:blinkon0
" Better line-height
set linespace=8
set lines=35 columns=150
" Hide UI elements
set guioptions-=r
set guioptions-=L
" Autoread
set autoread
