"Pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

"Turn off compatability mode
set nocompatible
filetype off
filetype plugin indent on

"Shows current typed command
set showcmd

"Set autoindentt
set autoindent

"Tab completion
set wildmenu
set wildmode=list:longest,full

"Optimize for fast terminal connections
set ttyfast

"Enable mouse support
set mouse=a

"Show line numbers
set number

"Don't add empty newlines at end of files
set binary
set noeol

"Don't create backups when editing files in certain directories
set backupskip=/tmp/*,/private/tmp/*

"Enable per-directory .vimrc files and disable unsafe commands in them
set exrc
set secure

"Remove buffer when closed
set nohidden

"Status line information
set laststatus=2
set statusline=%F%m%r%h%w\ (%{&ff}){%Y}\ [%l,%v][%p%%]

"Syntax highlighting
filetype plugin indent on
syntax on
set background=dark

"Color scheme
colorscheme seoul256

"Highlight current line
set cul

"Set tabs
set expandtab
"set tabstop=2
set shiftwidth=2
set softtabstop=2

"Ignore case of searches
set ignorecase

"Highlight dynamically as pattern is typed
set incsearch

"Show invisible characters
set lcs=tab:▸\ ,trail:·,nbsp:_
set list

" Show the cursor position
set ruler

"Show the current mode
set showmode

"Show the (partial) command as it's being typed
set showcmd

"Allow deleting previous items and indents
set backspace=indent,eol,start

"Find path settings
set path=$PWD/**

" show trailing spaces as dots
set listchars+=trail:·

"Key remaps
nnoremap <C-Q> <C-L>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"Change split behavior
set splitbelow
set splitright

"ctrlp
"set runtimepath^=~/.vim/bundle/ctrlp.vim

"ctrlp only searches working directory
let g:ctrlp_working_path_mode = 0

"ignore certain directories and files
set wildignore+=*/node_modules/*,*/.git/*,*/tmp/*,*.so,*.swp,*.zip

"js syntax
":autocmd Syntax * call SyntaxRange#Include('@begin=js@', '@end=js@', 'javascript', 'NonText')
":autocmd Syntax * call SyntaxRange#Include('@begin=bash@', '@end=bash@', 'sh', 'NonText')

"orgmode agenda
let g:org_agenda_files = ['~/Dropbox/orgmode/*.org']
